[tool.poetry]
name = "data-script"
version = "0.1.0"
description = ""
authors = ["kyomi <me@kyomi.dev>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
